name: Build APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # Using the official Kivy action with the correct path
        uses: kivy/buildozer-action@master
        with:
          command: buildozer android debug
          buildozer_version: master
